# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Build & deploy
      - name: Deploy to gh-pages branch
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}